### ISSUE TITLE
Default version (1.6) no longer exists

### ISSUE THREAD

**Issue by dougharris** [jmckib/django_docs_version_switcher#3]
After installing this, the `localStorage` element used to remember the desired django version doesn't exist, so the code sets it to 1.6. The Django documentation site no longer has that version of the code and returns a 404 page without the version switcher.

The **immediate user fix** is to open dev tools and set the `django_version` local storage item to 1.7 or newer.

The **quick fix for the code** is to change the default to 1.10 (currently the newest version).

The **slightly better fix for the code** is to change the code to _detect_ if the version doesn't exist and, if so, execute some sort of HTTP request to identify a valid version.

**Comment by dougharris** [comment]
Have a pull request https://github.com/jmckib/django_docs_version_switcher/pull/4

**Comment by jmckib** [comment]
Thanks for the fix!
